#ifndef DEFINES_H
#define DEFINES_H

#include <cstdint>

// A LITTLE NOTE FOR EVERYONE
// LIMIT OF 1 BYTE:  uint8_t  = 0 - 255 (INCLUSIVE)
// LIMIT OF 2 BYTES: uint16_t = 0 - 65,535 (INCLUSIVE)
// LIMIT OF 4 BYTES: uint32_t = 0 - 4,294,967,295 (INCLUSIVE)
// LIMIT OF 8 BYTES: uint64_t = 0 - 18,446,744,073,709,551,615 (INCLUSIVE)

// SIMULATION PARAMETERS | MODIFY WITH CARE | Chhu lo, magar pyar sy :)
// WHAT I MEAN IS, BEFORE CHANGING ANY VALUE, RE-CHECK THE DATA TYPE OF THAT VARIABLE AND ALL OTHER VARIABLES THAT DEPEND ON THAT
// OTHERWISE SIMULATION WILL JUST CRASH, OR BEHAVE ABNORMALLY

// WINDOW RELATED
constexpr uint16_t SCREEN_WIDTH = 1465;
constexpr uint16_t SCREEN_HEIGHT = 785;

#endif
